[package]
name = "qr_terminal"
version = "0.1.0"
authors = ["calum"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode = "0.11"
terminal_graphics = "*"
